# Generated by Django 5.2.5 on 2025-08-10 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=15, unique=True)),
                ('Name', models.CharField(max_length=30)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('Number', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DC', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', to_field='Account')),
            ],
        ),
    ]
