# Generated by Django 5.2.5 on 2025-08-10 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Account',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]{15}$', 'Must be exactly 15 alphanumeric characters.')]),
        ),
    ]
