# Generated by Django 5.2.5 on 2025-08-10 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Reference',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]{10}$', 'Must be exactly 10 alphanumeric characters.')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
